### ISSUE TITLE
Checkpoint 1 - instructor feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [kkelm/adhound#1]
Let me know when you are ready with checkpoint 1 items (I realize I'm looking at this before it's really due!)

- [ ] Problem statement
- [ ] user stories
- [ ] project plan
- [ ]  screen design
- [ ] timelog/journal/reflection statement 
- [ ] identify which stories are part of the Minimum Viable Product (MVP).

**Comment by kkelm** [comment]
I will. I just sat down to work on it some more, and I think I'm close.

**Comment by kkelm** [comment]
I think I'm ready. It's just a start, but at least it's something. I'm trying to keep most under the Wiki section so I'm not committing so much. https://github.com/kkelm/adhound/wiki Also, the user stories I'll have to show you tonight, since I didn't setup an educational account with Jira so it won't let me share the information publicly.

**Comment by pawaitemadisoncollege** [comment]
Good use of the wiki! It would be a good idea to put a link to it on the readme.md so that people know where to find all those design documents.  Can you put a screenshot of the user stories in the appropriate place in the wiki? That way I, your peers, and prospective employers can see that info at any time.

**Comment by pawaitemadisoncollege** [comment]
- [ ] Problem statement, looks solid, just one typo: "I was **_approach_** "
- [ ] Project plan may not be current, has references to trails ;)
- [ ] Which web service/api are you planning to use? Should be included in the technologies list. 
- [ ] Maybe technologies should be it's own page in the wiki?
- [ ] Nice job getting the DB design already - note that we'll need a role table (required for tomcat authentication). There are details about that in slack. 
- [ ] Are there screens detailing what the fields will be for adding the various items (ad, locations, etc).
